### ISSUE TITLE
Elementor Plugin

### ISSUE THREAD

**Issue by yaroslav-borodii** [JDI-company/Smart-Phone-for-Ninja-Forms#2]
# User Request
> I've been using the Smart Phone Addon for Ninja Forms plugin for my ninja forms, and I'm finding it makes some functionalities from the Elementor Builder plugin crash. Making them unusable, or not letting the Elementor plugin screens load at all. I've managed to deactivate your plugin temporarily while making elementor changes, but I'm wondering if there's anything else that could be causing the issues, or if you've stumbled upon other users having similar issues.

**Comment by roman1923** [comment]
When using Elementor v3.12.1 with Ninja Forms v3.6.21 and Smart Phone Addon for Ninja Forms v1.0.3 installed, based on WordPress v6.2 on PHP v8.0.28 and MySQL v10.6.12, no problems using or displaying Elementor or its widgets was not.

**Comment by yaroslav-borodii** [comment]
Dear user,

I apologize for the closure of your GitHub ticket. Our team was unable to reproduce the reported issue, leading to the decision to close it temporarily.

Thank you for your understanding and patience.

Kind regards,
Yaroslav Borodii
