### ISSUE TITLE
Does not determine the IP address of the user's country

### ISSUE THREAD

**Issue by vizhvizh** [JDI-company/Smart-Phone-for-Ninja-Forms#40]
Hi. There is no automatic substitution of the flag and country code, always selects the default country +44 United Kingdom. I tried it from different IP addresses, but it doesn't work.
The checkbox for Allow IP Lookup and SHOW SELECTED DIAL CODE is set. How to fix it?

Wordpress 6.4.3
PHP 7.4

**Comment by yaroslav-borodii** [comment]
Hey @vizhvizh!

Thanks for reaching out. We're aware of the issue with the automatic substitution of the flag and country code not working as expected, and we're on it! Could you please check if plugin is up to date in the meantime? We'll get back to you with an update as soon as possible.

**Comment by yaroslav-borodii** [comment]
Hey @vizhvizh!

Thanks for your patience!

We have successfully finished and closed this issue.
It's coming in v1.4.0. Follow our updates this week.
